// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: api/registry/service_v1.proto

package service_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProtoRegistryClient is the client API for ProtoRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProtoRegistryClient interface {
	// Список проектов
	GetProjects(ctx context.Context, in *GetProjectsRequest, opts ...grpc.CallOption) (*GetProjectsResponse, error)
	// Детальная информация о проекте
	GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*GetProjectResponse, error)
	// Зарегистрировать проект
	RegisterProject(ctx context.Context, in *RegisterProjectRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Список версий
	GetVersions(ctx context.Context, in *GetVersionsRequest, opts ...grpc.CallOption) (*GetVersionsResponse, error)
	// Детальная информация о версии
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error)
	// Список файлов
	GetFiles(ctx context.Context, in *GetFilesRequest, opts ...grpc.CallOption) (*GetFilesResponse, error)
	// Детальное представление файла
	GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error)
	// Зарегистрировать файлы
	RegisterFiles(ctx context.Context, in *RegisterFilesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type protoRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewProtoRegistryClient(cc grpc.ClientConnInterface) ProtoRegistryClient {
	return &protoRegistryClient{cc}
}

func (c *protoRegistryClient) GetProjects(ctx context.Context, in *GetProjectsRequest, opts ...grpc.CallOption) (*GetProjectsResponse, error) {
	out := new(GetProjectsResponse)
	err := c.cc.Invoke(ctx, "/services.v1.ProtoRegistry/GetProjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoRegistryClient) GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*GetProjectResponse, error) {
	out := new(GetProjectResponse)
	err := c.cc.Invoke(ctx, "/services.v1.ProtoRegistry/GetProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoRegistryClient) RegisterProject(ctx context.Context, in *RegisterProjectRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/services.v1.ProtoRegistry/RegisterProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoRegistryClient) GetVersions(ctx context.Context, in *GetVersionsRequest, opts ...grpc.CallOption) (*GetVersionsResponse, error) {
	out := new(GetVersionsResponse)
	err := c.cc.Invoke(ctx, "/services.v1.ProtoRegistry/GetVersions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoRegistryClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	out := new(GetVersionResponse)
	err := c.cc.Invoke(ctx, "/services.v1.ProtoRegistry/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoRegistryClient) GetFiles(ctx context.Context, in *GetFilesRequest, opts ...grpc.CallOption) (*GetFilesResponse, error) {
	out := new(GetFilesResponse)
	err := c.cc.Invoke(ctx, "/services.v1.ProtoRegistry/GetFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoRegistryClient) GetFile(ctx context.Context, in *GetFileRequest, opts ...grpc.CallOption) (*GetFileResponse, error) {
	out := new(GetFileResponse)
	err := c.cc.Invoke(ctx, "/services.v1.ProtoRegistry/GetFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoRegistryClient) RegisterFiles(ctx context.Context, in *RegisterFilesRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/services.v1.ProtoRegistry/RegisterFiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProtoRegistryServer is the server API for ProtoRegistry service.
// All implementations must embed UnimplementedProtoRegistryServer
// for forward compatibility
type ProtoRegistryServer interface {
	// Список проектов
	GetProjects(context.Context, *GetProjectsRequest) (*GetProjectsResponse, error)
	// Детальная информация о проекте
	GetProject(context.Context, *GetProjectRequest) (*GetProjectResponse, error)
	// Зарегистрировать проект
	RegisterProject(context.Context, *RegisterProjectRequest) (*emptypb.Empty, error)
	// Список версий
	GetVersions(context.Context, *GetVersionsRequest) (*GetVersionsResponse, error)
	// Детальная информация о версии
	GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error)
	// Список файлов
	GetFiles(context.Context, *GetFilesRequest) (*GetFilesResponse, error)
	// Детальное представление файла
	GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error)
	// Зарегистрировать файлы
	RegisterFiles(context.Context, *RegisterFilesRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedProtoRegistryServer()
}

// UnimplementedProtoRegistryServer must be embedded to have forward compatible implementations.
type UnimplementedProtoRegistryServer struct {
}

func (UnimplementedProtoRegistryServer) GetProjects(context.Context, *GetProjectsRequest) (*GetProjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjects not implemented")
}
func (UnimplementedProtoRegistryServer) GetProject(context.Context, *GetProjectRequest) (*GetProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProject not implemented")
}
func (UnimplementedProtoRegistryServer) RegisterProject(context.Context, *RegisterProjectRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterProject not implemented")
}
func (UnimplementedProtoRegistryServer) GetVersions(context.Context, *GetVersionsRequest) (*GetVersionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersions not implemented")
}
func (UnimplementedProtoRegistryServer) GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedProtoRegistryServer) GetFiles(context.Context, *GetFilesRequest) (*GetFilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFiles not implemented")
}
func (UnimplementedProtoRegistryServer) GetFile(context.Context, *GetFileRequest) (*GetFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFile not implemented")
}
func (UnimplementedProtoRegistryServer) RegisterFiles(context.Context, *RegisterFilesRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterFiles not implemented")
}
func (UnimplementedProtoRegistryServer) mustEmbedUnimplementedProtoRegistryServer() {}

// UnsafeProtoRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProtoRegistryServer will
// result in compilation errors.
type UnsafeProtoRegistryServer interface {
	mustEmbedUnimplementedProtoRegistryServer()
}

func RegisterProtoRegistryServer(s grpc.ServiceRegistrar, srv ProtoRegistryServer) {
	s.RegisterService(&ProtoRegistry_ServiceDesc, srv)
}

func _ProtoRegistry_GetProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoRegistryServer).GetProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.v1.ProtoRegistry/GetProjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoRegistryServer).GetProjects(ctx, req.(*GetProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtoRegistry_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoRegistryServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.v1.ProtoRegistry/GetProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoRegistryServer).GetProject(ctx, req.(*GetProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtoRegistry_RegisterProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoRegistryServer).RegisterProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.v1.ProtoRegistry/RegisterProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoRegistryServer).RegisterProject(ctx, req.(*RegisterProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtoRegistry_GetVersions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoRegistryServer).GetVersions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.v1.ProtoRegistry/GetVersions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoRegistryServer).GetVersions(ctx, req.(*GetVersionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtoRegistry_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoRegistryServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.v1.ProtoRegistry/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoRegistryServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtoRegistry_GetFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoRegistryServer).GetFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.v1.ProtoRegistry/GetFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoRegistryServer).GetFiles(ctx, req.(*GetFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtoRegistry_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoRegistryServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.v1.ProtoRegistry/GetFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoRegistryServer).GetFile(ctx, req.(*GetFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProtoRegistry_RegisterFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterFilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtoRegistryServer).RegisterFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.v1.ProtoRegistry/RegisterFiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtoRegistryServer).RegisterFiles(ctx, req.(*RegisterFilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProtoRegistry_ServiceDesc is the grpc.ServiceDesc for ProtoRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProtoRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.v1.ProtoRegistry",
	HandlerType: (*ProtoRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProjects",
			Handler:    _ProtoRegistry_GetProjects_Handler,
		},
		{
			MethodName: "GetProject",
			Handler:    _ProtoRegistry_GetProject_Handler,
		},
		{
			MethodName: "RegisterProject",
			Handler:    _ProtoRegistry_RegisterProject_Handler,
		},
		{
			MethodName: "GetVersions",
			Handler:    _ProtoRegistry_GetVersions_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _ProtoRegistry_GetVersion_Handler,
		},
		{
			MethodName: "GetFiles",
			Handler:    _ProtoRegistry_GetFiles_Handler,
		},
		{
			MethodName: "GetFile",
			Handler:    _ProtoRegistry_GetFile_Handler,
		},
		{
			MethodName: "RegisterFiles",
			Handler:    _ProtoRegistry_RegisterFiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/registry/service_v1.proto",
}
